# -*- coding: utf-8 -*-
"""SimpleEDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18olv0ma-RDf5C0MYr0BJ0ih9CChA0TCl
"""

#!pip install streamlit
#!pip install seaborn
#!pip install matplotlib
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Title
st.title("Simple Data Analysis App")

# File uploader
uploaded_file = st.file_uploader("Upload CSV or Excel file", type=["csv", "xlsx"])

if uploaded_file is not None:
    # Read file
    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)

    # Show raw data
    st.subheader("Raw Data")
    st.write(df.head())

    # Basic stats
    st.subheader("Summary Statistics")
    st.write(df.describe())

    # Column selection
    st.subheader("Visualisation")
    column = st.selectbox("Select column to plot", df.columns)

    # Plot histogram
    fig, ax = plt.subplots()
    sns.histplot(df[column], kde=True, ax=ax)
    st.pyplot(fig)

